# Global constants – mirrors RepoConsts.java

# Product states
STATE_DRAFT = "DRAFT"
STATE_IN_VALIDATION = "IN_VALIDATION"
STATE_VALIDATED = "VALIDATED"
STATE_ARCHIVED = "ARCHIVED"

# Formulation chain IDs
DEFAULT_CHAIN_ID = "default"
FAST_CHAIN_ID = "fastFormulationChain"

# Formulation result statuses
FORMULATION_OK = "OK"
FORMULATION_ERROR = "ERROR"
FORMULATION_WARNING = "WARNING"

# NutriScore grades
NUTRI_SCORE_A = "A"
NUTRI_SCORE_B = "B"
NUTRI_SCORE_C = "C"
NUTRI_SCORE_D = "D"
NUTRI_SCORE_E = "E"

# Allergen types
ALLERGEN_GLUTEN = "GLUTEN"
ALLERGEN_EGGS = "EGGS"
ALLERGEN_MILK = "MILK"
ALLERGEN_NUTS = "NUTS"
ALLERGEN_SOY = "SOY"
ALLERGEN_FISH = "FISH"
ALLERGEN_SHELLFISH = "SHELLFISH"
ALLERGEN_SESAME = "SESAME"

# Audit actions
AUDIT_CREATE = "CREATE"
AUDIT_UPDATE = "UPDATE"
AUDIT_DELETE = "DELETE"
AUDIT_FORMULATE = "FORMULATE"
AUDIT_TRANSITION = "WORKFLOW_TRANSITION"
AUDIT_QUALITY_CHECK = "QUALITY_CHECK"

# Quality check types
CHECK_COMPOSITION = "COMPOSITION_VALIDATION"
CHECK_ALLERGEN = "ALLERGEN_CHECK"
CHECK_NUTRIENT = "NUTRIENT_COMPLIANCE"
CHECK_COST = "COST_VALIDATION"

# Batch processing
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Report types
REPORT_PRODUCT_SHEET = "PRODUCT_SHEET"
REPORT_NUTRITION_FACTS = "NUTRITION_FACTS"
REPORT_ALLERGEN_SUMMARY = "ALLERGEN_SUMMARY"
